#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Builds data/spots.json for the Tibia Hunting Spot finder.

DATA SOURCES (values are community measurements, not CipSoft-official):
 - TibiaPal.com  /hunting tables (raw exp/h + loot/h per vocation & level;
   note: TibiaPal marks its data as pre "Vocation Rebalance 2026").
 - Intibia.com   /hunts (min level, exp ranges, profit ranges, access).
 - TibiaRoute.com (spot articles / routes).
 - tibiamaps.io marker data for real in-game coordinates (CC-BY-SA fan project).
Anything not directly sourced is tagged dataQuality="estimate".
"""
import json, os, copy

TODAY = "23.09.2026"

# ---------------------------------------------------------------- utilities
TP = {"label": "TibiaPal.com (pomiary społeczności)", "url": "https://tibiapal.com/hunting"}
IN = {"label": "Intibia.com (hunts)", "url": "https://intibia.com/hunts"}
TR = {"label": "TibiaRoute.com", "url": "https://tibiaroute.com"}
TM = {"label": "tibiamaps.io (współrzędne)", "url": "https://tibiamaps.io"}

def stat(v, lvl, xp=None, profit=None, q="measured"):
    return {"vocation": v, "minLevel": lvl, "xph": xp, "profit": profit, "quality": q}

SPOTS = []

def spot(**kw):
    base = dict(
        quests=[], access=[], modes=["solo", "duo", "party"], partyRec=None, pacc=True,
        difficulty=3, risk=3, damageTypes=["physical"], resistances=[],
        gear=[], spells=[], runes=[], potions=[], pulling="", rotation="",
        bestTime="", alternatives=[], video=None, extra_sources=[],
        dataQuality="measured", lastUpdated=TODAY,
    )
    base.update(kw)
    SPOTS.append(base)

# ================================================================ LOW LEVEL
spot(id="targuna-lizards", name="Targuna — Jaszczury", region="Tiquanda", continent="Tiquanda",
     city="Port Hope", coords={"x":32560,"y":32820,"z":7,"approx":True},
     levelMin=8, levelMax=40, recLevel="8–40",
     vocations=["EK","RP","MS","MNK"],
     description="Wyspa/obszar Targuna koło Port Hope: jaszczury i piraci. Jeden z najlepszych startowych spawnów po Rookgaardzie, bardzo bezpieczny i dochodowy dla młodych profesji.",
     stats=[stat("EK",8,45000,45000), stat("RP",8,60000,55000), stat("MS",8,55000,50000), stat("MNK",8,50000,50000,"estimate")],
difficulty=1, risk=1,
     damageTypes=["physical"], resistances=["physical"],
     monsters=[{"name":"Lizard Templar","slug":"lizard-templar"},{"name":"Lizard Snakecharmer","slug":"lizard-snakecharmer"},{"name":"Lizard Sentinel","slug":"lizard-zaogun"}],
     gear=["Zbroja skórzana / ćwiekowana","Broń jednoręczna + tarcza (EK/RP: spear)"],
     spells=["Exura (ED/MS wsparcie)","Atak podstawowy"],
     potions=["Mana potion / health potion (małe)"],
     pulling="Pulluj pojedynczo przy wejściu do ruin; jaszczury nie gonią daleko.",
     rotation="Kółko po powierzchni wyspy, omijaj skupiska 3+ potworów na niskim levelu.",
     hero=None, sources=[TP,TM],
     alternatives=["swamp-trolls","amazon-camp","cyclops-mistrock"])

spot(id="swamp-trolls", name="Swamp Trolls (Port Hope / Venore)", region="Tiquanda / okolice Venore", continent="Tiquanda",
     city="Port Hope", coords={"x":32610,"y":32770,"z":9,"approx":True},
     levelMin=8, levelMax=25, recLevel="8–25",
     vocations=["EK","RP","MS","MNK","ED"],
     description="Klasyczny startowy spawn bagiennych trolli w jaskiniach koło Port Hope i Venore. Minimalne ryzyko, delikatny plus profitu — idealny na pierwsze levele i trening skilli.",
     stats=[stat("EK",8,30000,50000), stat("RP",8,30000,55000), stat("MS",8,30000,50000)],
     difficulty=1, risk=1, damageTypes=["physical"],
     monsters=[{"name":"Swamp Troll","slug":"swamp-troll"},{"name":"Troll","slug":"troll"}],
     gear=["Podstawowa broń + tarcza"], potions=["Health potion"],
     pulling="Ciągnij po 2–3 do wejścia, trollki biją bardzo słabo.",
     rotation="Czyszczaj kolejne pokoje jaskini po pętli.",
     hero=None, sources=[TP,TM], alternatives=["targuna-lizards","rotworms-liberty-bay"])

spot(id="rotworms-liberty-bay", name="Rotwormy (Liberty Bay / Darashia)", region="Liberty Bay / Darama", continent="Tiquanda / Darama",
     city="Liberty Bay", coords={"x":32330,"y":32810,"z":9,"approx":True},
     levelMin=8, levelMax=20, recLevel="8–20",
     vocations=["EK","RP","MS","ED"],
     description="Podziemne tunele z rotwormami koło Liberty Bay oraz piaski Darashii. Zerowy profit, ale bezpieczny exp i trening dla świeżych postaci.",
     stats=[stat("MS",8,40000,0), stat("EK",8,35000,0,"estimate")],
     difficulty=1, risk=1, damageTypes=["physical"],
     monsters=[{"name":"Rotworm","slug":"rotworm"},{"name":"Carrion Worm","slug":"rotworm"}],
     gear=["Broń startowa + tarcza"], potions=["Health potion"],
     pulling="Rotwormy są wolne — łatwo kitingować na korytarzu.",
     rotation="Pętla po górnych tunelach, bez schodzenia na niższe pietra.",
     hero=None, sources=[TP], alternatives=["swamp-trolls","targuna-lizards"])

spot(id="cyclops-mistrock", name="Cyclops Mistrock", region="Wyspa Mistrock", continent="Tiquanda",
     city="Venore", coords={"x":32800,"y":32130,"z":7,"approx":True},
     levelMin=13, levelMax=40, recLevel="13–40",
     vocations=["MNK","EK","MS"],
     description="Mała wyspa z cyklopami — kultowy spawn dla monków i niskopoziomowych knightów. Prosty teren, łatwe pullowanie, przyzwoity exp jak na ten przedział.",
     stats=[stat("MNK",13,75000,15000), stat("MS",13,75000,15000)],
     difficulty=2, risk=2, damageTypes=["physical"],
     monsters=[{"name":"Cyclops","slug":"cyclops"},{"name":"Cyclops Drone","slug":"cyclops-drone"}],
     gear=["Broń + tarcza, plate armor jeśli dostępny"],
     pulling="Wycofuj się na plażę przy 3+ cyklopach.",
     rotation="Okrążaj wyspę, czyść jaskinie od wejścia.",
     hero=None, sources=[TP], alternatives=["targuna-lizards","amazon-camp"])

spot(id="amazon-camp", name="Amazon Camp (Venore)", region="Bagna Venore", continent="Tiquanda",
     city="Venore", coords={"x":32850,"y":32080,"z":7,"approx":True},
     levelMin=15, levelMax=40, recLevel="15–40",
     vocations=["RP","MS","MNK"],
     description="Obóz amazonek i valkyrii na bagnach pod Venore. Bardzo dobry profit z lootu (speary, ochronne itemy), lekki exp.",
     stats=[stat("RP",15,35000,60000), stat("MS",8,45000,125000), stat("MNK",15,40000,60000,"estimate")],
     difficulty=1, risk=2, damageTypes=["physical"],
     monsters=[{"name":"Amazon","slug":"amazon"},{"name":"Valkyrie","slug":"valkyrie"}],
     gear=["Broń dystansowa / zaklęta, distance armor"],
     pulling="Valkyrie rzucają spearami — trzymaj dystans i zasłony.",
     rotation="Czyść polanę i chatki po kolei, nie wchodź do środka wieży na raz.",
     hero=None, sources=[TP], alternatives=["cyclops-mistrock","elves-yalahar"])

spot(id="elves-yalahar", name="Elfy Yalahar", region="Yalahar (okolice)", continent="Zao",
     city="Yalahar", coords={"x":32770,"y":31260,"z":7,"approx":True},
     levelMin=18, levelMax=45, recLevel="18–45",
     vocations=["EK","RP","MS","MNK"],
     description="Elfy i elfy arkańskie pod Yalaharem. Dobry exp i solidny profit z run i strzał dla postaci 18–45.",
     stats=[stat("RP",18,50000,40000), stat("MS",15,80000,150000), stat("MNK",15,80000,150000), stat("EK",18,45000,30000,"estimate")],
     difficulty=2, risk=2, damageTypes=["physical","energy","fire"],
     monsters=[{"name":"Elf","slug":"elf"},{"name":"Elf Arcanist","slug":"elf-arcanist"}],
     resistances=["energy"],
     pulling="Uważaj na arcanistów — mają fireball i icicle; pulluj zza drzew.",
     rotation="Pętla po lesie wokół ruin.",
     hero=None, sources=[TP], alternatives=["amazon-camp","coryms-port-hope"])

spot(id="coryms-port-hope", name="Corymy Port Hope", region="Tiquanda", continent="Tiquanda",
     city="Port Hope", coords={"x":32600,"y":32760,"z":9,"approx":True},
     levelMin=23, levelMax=70, recLevel="30–70",
     vocations=["EK","MS","RP"],
     description="Jaskinie corymów pod Port Hope. Z stealth ringiem dostępne już od ~23 lv; świetny stosunek expu do profitu dla EK/MS.",
     stats=[stat("EK",23,160000,120000), stat("MS",30,300000,300000), stat("RP",23,160000,120000,"estimate")],
     difficulty=2, risk=2, damageTypes=["physical","earth"],
     monsters=[{"name":"Corym Skirmisher","slug":"corym-skirmisher"},{"name":"Corym Vanguard","slug":"corym-vanguard"},{"name":"Corym Charlatan","slug":"corym-charlatan"}],
     access=["Stealth Ring (do dolnych części)"],
     pulling="Skirmisherzy szybko biją — nie daj się otoczyć w wąskich korytarzach.",
     rotation="Pętla po głównych salach, pomijaj boczne odnogi przy słabszym sprzędzie.",
     hero=None, sources=[TP], alternatives=["gargoyle-cave-meriana","mosl-3"])

spot(id="gargoyle-cave-meriana", name="Meriana Gargoyle Cave", region="Laguna Islands", continent="Tiquanda",
     city="Meriana", coords={"x":32389,"y":32604,"z":7,"approx":False},
     levelMin=28, levelMax=65, recLevel="30–60",
     vocations=["MS","EK","RP"],
     description="Jaskinia gargulców na wyspie Meriana. Świetny profit (kamienne itemy) i stabilny exp; wejście oznaczone na mapie tibiamaps.",
     stats=[stat("MS",28,210000,300000), stat("EK",28,150000,250000,"estimate")],
     difficulty=2, risk=2, damageTypes=["physical","earth"],
     monsters=[{"name":"Gargoyle","slug":"gargoyle"},{"name":"Stone Golem","slug":"stone-golem"}],
     resistances=["earth","physical"],
     pulling="Gargulce są wolne — pulluj po 2–3 do korytarza.",
     rotation="Jedna pętla po jaskini, zejścia tylko przy 40+.",
     hero=None, sources=[TP,TM], alternatives=["laguna-islands","mosl-3"])

spot(id="laguna-islands", name="Laguna Islands (Blood Crabs)", region="Laguna Islands", continent="Tiquanda",
     city="Meriana", coords={"x":31946,"y":31902,"z":7,"approx":False},
     levelMin=30, levelMax=60, recLevel="30–60",
     vocations=["MS","RP","EK"],
     description="Wyspy laguny z blood crabami — profitowa perełka dla 30–60. Loot z krabów pokrywa koszty i daje solidny plus.",
     stats=[stat("MS",30,210000,500000), stat("RP",50,170000,500000)],
     difficulty=2, risk=2, damageTypes=["physical"],
     monsters=[{"name":"Blood Crab","slug":"blood-crab"}],
     pulling="Krabów jest dużo — używaj fal/obszarówek i trzymaj dystans.",
     rotation="Plaża → laguna → powrót łodzią; nie walcz w wodzie.",
     hero="laguna.jpg", video={"title":"Laguna Islands (TibiaPal)","url":"https://youtu.be/iy119L5l8vo"},
     sources=[TP,TM], alternatives=["gargoyle-cave-meriana","mosl-3"])

spot(id="mosl-3", name="Mother of Scarabs Lair –3 (Mummy/Bonebeasts)", region="Ankrahmun Tombs", continent="Darama",
     city="Ankrahmun", coords={"x":33160,"y":32780,"z":10,"approx":True},
     levelMin=30, levelMax=80, recLevel="40–70",
     vocations=["MS","RP","EK","MNK"],
     description="Trzecie piętro legowiska Matki Skarabeuszy: mumie i bonebeasty. Klasyczny spawn dla 40–70 z bardzo dobrym profitem.",
     stats=[stat("MS",30,270000,400000), stat("RP",40,190000,200000), stat("EK",30,180000,150000,"estimate")],
     difficulty=3, risk=3, damageTypes=["death","physical"],
     monsters=[{"name":"Mummy","slug":"mummy"},{"name":"Bonebeast","slug":"demon-skeleton"},{"name":"Scarab","slug":"scarab"}],
     resistances=["death"],
     runes=["Avalanche / Stone Shower (RP/MS)"],
     pulling="Bonebeasty paraliżują — miej zawsze exana lub paralyze counter.",
     rotation="Pętla po komnatach –3, drzwi zamykaj za sobą.",
     hero="mosl3.jpg", video={"title":"MoSL -3 (TibiaPal)","url":"https://youtu.be/MZueW2hDi4s"},
     sources=[TP,TM], alternatives=["putrid-mummy","putrid-mummy","peninsula-tomb"])

spot(id="upper-spike", name="Upper Spike", region="The Spike", continent="Tiquanda",
     city="Ab'Dendriel", coords={"x":32624,"y":31854,"z":8,"approx":False},
     levelMin=30, levelMax=60, recLevel="30–60",
     vocations=["MS","MNK","EK"],
     description="Górne pietra The Spike — zadaniowego dungeonu pod Ab'Dendriel. Wymaga rozpoczęcia questa The Spike, daje świetny exp dla 30–60.",
     stats=[stat("MS",30,290000,250000), stat("MNK",30,290000,250000)],
     quests=["The Spike Quest (dostęp do odpowiednich pięter)"],
     difficulty=3, risk=3, damageTypes=["physical","earth","energy"],
     monsters=[{"name":"Spikes creatures","slug":"walker"},{"name":"Glooth Blob","slug":"glooth-blob"}],
     pulling="Zadania Spike wymuszają walkę w grupach — zabierz runy obszarowe.",
     rotation="Wykonuj taski po kolei, exp przy okazji.",
     hero="upper-spike.jpg", video={"title":"Upper Spike (TibiaPal)","url":"https://youtu.be/C-3lqdyhFdI"},
     sources=[TP,TM], alternatives=["middle-spike","coryms-port-hope"])

# ================================================================ MID 40-80
spot(id="darashia-dragon-lair", name="Darashia Dragon Lair (Kha'Zeel)", region="Kha'Zeel / Darama", continent="Darama",
     city="Darashia", coords={"x":33009,"y":32604,"z":7,"approx":False},
     levelMin=40, levelMax=80, recLevel="50–80",
     vocations=["EK","RP","MS"],
     description="Północne legowisko smoków w górach Kha'Zeel nad Darashią. Klasyk dla EK/RP 40–80; wejście oznaczone markerem 'Northern Kha'zeel Dragon Lair'.",
     stats=[stat("RP",40,220000,0), stat("EK",50,250000,10000,"estimate"), stat("MS",50,260000,-20000,"estimate")],
     difficulty=3, risk=3, damageTypes=["fire","physical"],
     monsters=[{"name":"Dragon","slug":"dragon"},{"name":"Dragon Hatchling","slug":"dragon-hatchling"}],
     resistances=["fire"],
     gear=["Zbroja z fire protection (np. dragon scale mail później)"],
     potions=["Strong health potion"],
     pulling="Smoki zieją ogniem w stożku — nie stój w linii prostej.",
     rotation="Wejście → lewa komnata → prawa → wycofanie po schodach.",
     hero=None, sources=[TP,TM], alternatives=["yalahar-dragons","fenrock-dragon-lords"])

spot(id="yalahar-dragons", name="Yalahar Dragons", region="Yalahar", continent="Zao",
     city="Yalahar", coords={"x":32780,"y":31280,"z":9,"approx":True},
     levelMin=40, levelMax=80, recLevel="40–80",
     vocations=["RP","EK","MS"],
     description="Smoki w podziemiach pod Yalaharem. Dobry exp dla paladynów od 40 lv, lekki minus profitu.",
     stats=[stat("RP",40,250000,10000), stat("EK",50,230000,10000,"estimate")],
     difficulty=3, risk=3, damageTypes=["fire","physical"],
     monsters=[{"name":"Dragon","slug":"dragon"},{"name":"Dragon Hatchling","slug":"dragon-hatchling"}],
     resistances=["fire"],
     pulling="Używaj korytarzy do pojedynczych pulli.",
     rotation="Pętla po dwóch salach, powrót na górę po refill.",
     hero=None, sources=[TP], alternatives=["darashia-dragon-lair","fenrock-dragon-lords"])

spot(id="edron-fortress-bonebeasts", name="Edron Old Fortress –1 (Bonebeasts)", region="Edron", continent="Edron",
     city="Edron", coords={"x":33190,"y":31780,"z":8,"approx":True},
     levelMin=40, levelMax=70, recLevel="40–70",
     vocations=["RP","EK","MNK"],
     description="Ruiny starej fortecy na Edronie, piętro –1 z bonebeastami. Bardzo tani hunt dla paladynów (prawie zerowy koszt).",
     stats=[stat("RP",40,330000,30000), stat("EK",50,250000,10000,"estimate"), stat("MNK",50,300000,20000,"estimate")],
     difficulty=2, risk=2, damageTypes=["death","physical"],
     monsters=[{"name":"Bonebeast","slug":"demon-skeleton"},{"name":"Skeleton","slug":"skeleton"}],
     resistances=["death"],
     pulling="Bonebeasty trują — miej antidote/antidote rune.",
     rotation="Czyść dziedziniec i lochy –1 osobno.",
     hero=None, sources=[TP], alternatives=["edron-heroes","edron-vampire-crypt"])

spot(id="lions-rock", name="Lion's Rock", region="Darama (pustynia)", continent="Darama",
     city="Darashia", coords={"x":33080,"y":32530,"z":8,"approx":True},
     levelMin=50, levelMax=90, recLevel="55–85",
     vocations=["RP","MS","EK"],
     description="Świątynia lwów na pustyni — mieszany spawn z lionami i kultystami. Wysoki exp od 50+, profit bliski zera.",
     stats=[stat("RP",60,480000,30000), stat("MS",55,470000,-15000)],
     difficulty=3, risk=3, damageTypes=["physical","holy"],
     monsters=[{"name":"Lion","slug":"lion"},{"name":"Cult Scholar","slug":"cult-scholar"}],
     pulling="Nie otwieraj wszystkich drzwi naraz — lwy zbiegają się parami.",
     rotation="Główne piętro świątyni + korytarze boczne.",
     hero="lions-rock.jpg", video={"title":"Lion's Rock (TibiaPal)","url":"https://youtu.be/G6YfJSfhZFc"},
     sources=[TP], alternatives=["putrid-mummy","nibelor-crystal-spiders"])

spot(id="nibelor-crystal-spiders", name="Nibelor Crystal Spiders", region="Nibelor (okolice Svargrond)", continent="Svargrond",
     city="Svargrond", coords={"x":32300,"y":31050,"z":8,"approx":True},
     levelMin=50, levelMax=85, recLevel="55–80",
     vocations=["RP","MS","EK"],
     description="Lodowa wyspa Nibelor z crystal spiderami. Przyzwoity exp, słaby profit; uważaj na paralyze pająków.",
     stats=[stat("RP",60,400000,30000), stat("MS",55,450000,20000)],
     difficulty=3, risk=3, damageTypes=["ice","physical"],
     monsters=[{"name":"Crystal Spider","slug":"crystal-spider"},{"name":"Ice Golem","slug":"ice-golem"}],
     resistances=["ice"],
     pulling="Crystal spidery paralyze'ują — egzura i dystans.",
     rotation="Jaskinia główna, bez schodzenia do lodowych tuneli poniżej 60 lv.",
     hero="nibelor.jpg", video={"title":"Nibelor Crystal Spiders (TibiaPal)","url":"https://youtu.be/met-mJrmHCs"},
     sources=[TP], alternatives=["okolnir","sea-serpents"])

spot(id="wyrms-liberty-bay", name="Wyrms Liberty Bay –1", region="Liberty Bay", continent="Tiquanda",
     city="Liberty Bay", coords={"x":32340,"y":32810,"z":9,"approx":True},
     levelMin=50, levelMax=100, recLevel="60–95",
     vocations=["RP","MS","EK"],
     description="Podziemne legowisko wyrmów pod Liberty Bay. Mocny exp dla 50–100, profit bliski zera — typowy hunt 'na exp'.",
     stats=[stat("RP",50,350000,0), stat("MS",66,550000,-125000)],
     difficulty=3, risk=3, damageTypes=["energy","physical"],
     monsters=[{"name":"Wyrm","slug":"wyrm"}],
     resistances=["energy"],
     pulling="Wyrmy biją energią — energy protection bardzo pomaga.",
     rotation="Pętla po tunelu –1; nie wchodź na –2 poniżej 90 lv.",
     hero="wyrms-lb.jpg", video={"title":"Liberty Bay Wyrms (TibiaPal)","url":"https://youtu.be/mRSTM_17xVo"},
     sources=[TP], alternatives=["quaras-liberty-bay","exotic-cave"])

spot(id="edron-vampire-crypt", name="Edron Vampire Crypt", region="Edron", continent="Edron",
     city="Edron", coords={"x":33109,"y":31721,"z":7,"approx":False},
     levelMin=50, levelMax=140, recLevel="50–130",
     vocations=["EK","RP","MS"],
     description="Krypty wampirów na północno-zachodnim wybrzeżu Edronu (realne współrzędne markera 'Vampire Crypts'). Piętra –3/–4 to już exp dla 90+.",
     stats=[stat("RP",50,280000,100000), stat("RP",90,950000,400000), stat("MS",80,825000,300000), stat("EK",90,900000,300000,"estimate")],
     difficulty=3, risk=3, damageTypes=["death","physical"],
     monsters=[{"name":"Vampire","slug":"vampire"},{"name":"Vampire Bride","slug":"vampire-bride"},{"name":"Necromancer","slug":"necromancer"}],
     resistances=["death"],
     runes=["Holy Missile / San (RP)"],
     pulling="Wampiry lifedrainują — nie daj się zagnieździć w rogu.",
     rotation="–3 dla 50–90, –4 dla 90+ (tam więcej necromancerów).",
     hero="edron-vampire.jpg", video={"title":"Edron Vampire Crypt (TibiaPal)","url":"https://youtu.be/I46AvXl0MDQ"},
     sources=[TP,TM], alternatives=["grimvale-4","edron-were-south"])

spot(id="middle-spike", name="Middle Spike", region="The Spike", continent="Tiquanda",
     city="Ab'Dendriel", coords={"x":32624,"y":31854,"z":10,"approx":False},
     levelMin=50, levelMax=90, recLevel="50–85",
     vocations=["MS","MNK","EK"],
     description="Środkowe pietra The Spike. Wymaga kontynuacji questa, daje wyraźnie lepszy exp niż Upper Spike.",
     stats=[stat("MS",50,750000,150000), stat("MNK",50,750000,150000)],
     quests=["The Spike Quest (odpowiednie misje)"],
     difficulty=3, risk=3, damageTypes=["physical","energy"],
     monsters=[{"name":"Spikes creatures","slug":"walker"}],
     pulling="Taski Spike'a — walczysz falami, trzymaj rogi sal.",
     rotation="Wykonuj zadania pięter, czyść respawn przy okazji.",
     hero="middle-spike.jpg", video={"title":"Middle Spike (TibiaPal)","url":"https://youtu.be/OGrKZrJndBc"},
     sources=[TP,TM], alternatives=["upper-spike","lower-spike"])

spot(id="quaras-liberty-bay", name="Quary Liberty Bay", region="Liberty Bay (podwodnie)", continent="Tiquanda",
     city="Liberty Bay", coords={"x":32320,"y":32790,"z":10,"approx":True},
     levelMin=80, levelMax=130, recLevel="80–125",
     vocations=["RP","MS","EK"],
     description="Podwodne jaskinie quar pod Liberty Bay. Dobry exp i niezły profit, wymaga swobodnego nurkowania (depth ostra) i odporności na ice.",
     stats=[stat("RP",90,1200000,150000), stat("MS",80,975000,300000)],
     difficulty=3, risk=4, damageTypes=["ice","physical"],
     monsters=[{"name":"Quara Hydromancer","slug":"quara-hydromancer"},{"name":"Quara Predator","slug":"quara-predator"},{"name":"Quara Constrictor","slug":"quara-constrictor"}],
     resistances=["ice"],
     access=["Umiejętność oddychania pod wodą (helmet of the deep / depth gear)"],
     pulling="Predatory są szybkie — pulluj na krawędziach jaskiń.",
     rotation="Zewnętrzny pierścień jaskiń, centrum tylko w party.",
     hero="quaras-lb.jpg", video={"title":"Quaras Liberty Bay (TibiaPal)","url":"https://youtu.be/ZHmGGJb9wqw"},
     sources=[TP], alternatives=["yalahar-sunken-quarter","orlamond-west"])

spot(id="yalahar-cults", name="Yalahar Cults", region="Yalahar", continent="Zao",
     city="Yalahar", coords={"x":32760,"y":31250,"z":9,"approx":True},
     levelMin=50, levelMax=90, recLevel="55–85",
     vocations=["MS","RP","EK"],
     description="Kultyści w podziemiach Yalaharu. Zbalansowany exp i bardzo dobry profit z run oraz sprzętu kultystów.",
     stats=[stat("MS",50,380000,400000), stat("RP",60,350000,350000)],
     difficulty=3, risk=3, damageTypes=["physical","death"],
     monsters=[{"name":"Cult Enforcer","slug":"cult-enforcer"},{"name":"Cult Scholar","slug":"cult-scholar"},{"name":"Cult Believer","slug":"cult-believer"}],
     pulling="Kultyści wzywają posiłki — zabijaj Believerów w pierwszej kolejności.",
     rotation="Pętla po kanałach pod Foreigner Quarter.",
     hero=None, sources=[TP], alternatives=["carlin-cults","yalahar-dragons"])

spot(id="krailos-bug-cave", name="Krailos Bug Cave", region="Krailos", continent="Krailos",
     city="Krailos", coords={"x":32300,"y":31900,"z":9,"approx":True},
     levelMin=80, levelMax=130, recLevel="80–130",
     vocations=["EK","MS","RP"],
     description="Jaskinia insektoidów w Krailos. Solidny exp dla knightów 90+ i magów, przyzwoity profit.",
     stats=[stat("EK",90,1000000,200000,"estimate"), stat("MS",80,600000,300000)],
     difficulty=3, risk=3, damageTypes=["physical","earth"],
     monsters=[{"name":"Insectoid","slug":"bug"},{"name":"Wiggler","slug":"wiggler"}],
     resistances=["earth"],
     pulling="Insektoidy pojawiają się falami — kontroluj wejścia do komór.",
     rotation="Główna komnata + dwa boczne tunele.",
     hero="krailos-bug.jpg", video={"title":"Krailos Bug Cave (TibiaPal)","url":"https://youtu.be/Y7cITH0-AfI"},
     sources=[TP], alternatives=["krailos-nightmare-scions","muggy-plains"])

spot(id="giant-spiders-port-hope", name="Giant Spiders Port Hope", region="Tiquanda", continent="Tiquanda",
     city="Port Hope", coords={"x":32650,"y":32800,"z":8,"approx":True},
     levelMin=80, levelMax=140, recLevel="80–130",
     vocations=["EK","RP","MS"],
     description="Legowiska gigantycznych pająków w dżungli pod Port Hope. Klasyk 80+; dobry exp, niski profit, ryzyko paralyze.",
     stats=[stat("EK",80,900000,20000,"estimate"), stat("MS",80,600000,20000), stat("RP",80,700000,20000,"estimate")],
     difficulty=3, risk=4, damageTypes=["physical","earth"],
     monsters=[{"name":"Giant Spider","slug":"giant-spider"},{"name":"Tarantula","slug":"tarantula"}],
     resistances=["earth"],
     pulling="Giant spidery skaczą i paralyze'ują — miej exana gran.",
     rotation="Czyść pojedyncze gniazda, nie całe pole naraz.",
     hero=None, sources=[TP], alternatives=["muggy-plains","lizard-chosens"])

spot(id="muggy-plains", name="Muggy Plains", region="Tiquanda", continent="Tiquanda",
     city="Port Hope", coords={"x":32700,"y":32750,"z":7,"approx":True},
     levelMin=80, levelMax=150, recLevel="80–140",
     vocations=["RP","MS","EK"],
     description="Bagienne równiny między Port Hope a Banutą: jaszczury, pająki i were-stwory. Dobry exp + profit, popularny task spot.",
     stats=[stat("RP",90,1050000,400000), stat("MS",80,750000,500000)],
     difficulty=3, risk=3, damageTypes=["physical","earth"],
     monsters=[{"name":"Lizard Templar","slug":"lizard-templar"},{"name":"Giant Spider","slug":"giant-spider"},{"name":"Lizard Legionnaire","slug":"lizard-legionnaire"}],
     resistances=["earth"],
     pulling="Otwarty teren — kitinguj łukiem przy większych grupach.",
     rotation="Pętla wschód–zachód wzdłuż rzeki.",
     hero="muggy.jpg", video={"title":"Muggy Plains (TibiaPal)","url":"https://youtu.be/KLrdg9HVBVs"},
     sources=[TP], alternatives=["lizard-chosens","giant-spiders-port-hope"])

spot(id="hive-surface", name="Hive Surface", region="Hive (wyspa)", continent="Zao",
     city="—", coords={"x":33496,"y":31198,"z":3,"approx":False},
     levelMin=70, levelMax=150, recLevel="70–130",
     vocations=["RP","EK","MS"],
     description="Powierzchnia roju (Hive) — wymagany dostęp z questa The Hive. Dobry exp i profit dla 70+; głębsze pietra dla wyższych leveli.",
     stats=[stat("RP",70,550000,350000), stat("EK",80,700000,300000,"estimate")],
     quests=["The Hive Quest (dostęp)"],
     difficulty=3, risk=3, damageTypes=["physical","earth"],
     monsters=[{"name":"Kollos","slug":"kollos"},{"name":"Wiggler","slug":"wiggler"},{"name":"Hive creatures","slug":"bug"}],
     resistances=["earth"],
     pulling="Kollosy eksplodują po śmierci — trzymaj dystans.",
     rotation="Powierzchnia + stage 1; stage 2/3 dopiero 150+.",
     hero=None, sources=[TP,TM], alternatives=["draken-walls","orlamond-west"])

# ================================================================ 90-200
spot(id="sea-serpents", name="Sea Serpents (Svargrond)", region="Morze koło Svargrond", continent="Svargrond",
     city="Svargrond", coords={"x":32250,"y":31020,"z":9,"approx":True},
     levelMin=90, levelMax=160, recLevel="90–150",
     vocations=["EK","RP","MS"],
     description="Podwodne legowisko węży morskich na północ od Svargrondu. Klassyczny hunt 90–150 z walką o ice-resist.",
     stats=[stat("EK",90,1100000,100000,"estimate"), stat("RP",90,1000000,100000,"estimate"), stat("MS",90,950000,50000,"estimate")],
     dataQuality="estimate",
     difficulty=3, risk=3, damageTypes=["ice","physical"],
     monsters=[{"name":"Sea Serpent","slug":"sea-serpent"},{"name":"Young Sea Serpent","slug":"young-sea-serpent"}],
     resistances=["ice"],
     access=["Sprzęt do oddychania pod wodą"],
     pulling="Młode węże atakują falami — kontroluj przesmyki.",
     rotation="Pętla po zatopionych komnatach.",
     hero=None, sources=[TP,TM], alternatives=["nibelor-crystal-spiders","okolnir"])

spot(id="edron-heroes", name="Edron Old Fortress –2/–3 (Heroes)", region="Edron", continent="Edron",
     city="Edron", coords={"x":33190,"y":31780,"z":10,"approx":True},
     levelMin=90, levelMax=180, recLevel="90–160",
     vocations=["EK","RP","MS"],
     description="Głębokie piętra fortecy Edron z heroes i undead elite. Jeden z najlepszych huntów 90–160 dla EK/RP.",
     stats=[stat("RP",90,1750000,50000), stat("MS",120,1700000,100000), stat("EK",90,1600000,50000,"estimate")],
     difficulty=4, risk=4, damageTypes=["physical","holy","death"],
     monsters=[{"name":"Hero","slug":"hero"},{"name":"Necromancer","slug":"necromancer"},{"name":"Priestess","slug":"priestess"}],
     pulling="Heroes biją mocno fizycznie — EK trzyma aggro w korytarzu.",
     rotation="–2 dla 90–120, –3 od 120+ (tam priestessy).",
     hero="edron-heroes.jpg", video={"title":"Edron Old Fortress Heroes -2/-3 (TibiaPal)","url":"https://youtu.be/v8vZQViImYo"},
     sources=[TP], alternatives=["edron-fortress-bonebeasts","carlin-cults"])

spot(id="fenrock-dragon-lords", name="Fenrock Dragon Lords", region="Fenrock", continent="Zao",
     city="Yalahar", coords={"x":32830,"y":31300,"z":10,"approx":True},
     levelMin=90, levelMax=160, recLevel="90–150",
     vocations=["RP","EK","MS"],
     description="Legowisko dragon lordów w Fenrock. Dobry exp, zerowy profit — czysty grind pod level.",
     stats=[stat("RP",90,900000,0), stat("EK",90,850000,0,"estimate")],
     difficulty=3, risk=4, damageTypes=["fire"],
     monsters=[{"name":"Dragon Lord","slug":"dragon-lord"},{"name":"Dragon Lord Hatchling","slug":"dragon-lord-hatchling"}],
     resistances=["fire"],
     pulling="DL-e zieją ogniem w linii — chowaj się za filarami.",
     rotation="Główna jaskinia bez bocznych komór.",
     hero=None, sources=[TP], alternatives=["darashia-dragon-lords","yalahar-dragons"])

spot(id="darashia-dragon-lords", name="Darashia Dragon Lords", region="Kha'Zeel / Darama", continent="Darama",
     city="Darashia", coords={"x":33116,"y":32605,"z":8,"approx":False},
     levelMin=90, levelMax=160, recLevel="90–150",
     vocations=["RP","EK","MS"],
     description="Południowe legowisko w Kha'Zeel z dragon lordami (marker 'Dragon lair' na tibiamaps). Exp bez profitu, wysoka temperatura = fire protection.",
     stats=[stat("RP",90,750000,0), stat("EK",90,700000,0,"estimate")],
     difficulty=3, risk=4, damageTypes=["fire"],
     monsters=[{"name":"Dragon Lord","slug":"dragon-lord"}],
     resistances=["fire"],
     pulling="Pojedyncze pulle na schodach.",
     rotation="Jedna pętla po legowisku.",
     hero=None, sources=[TP,TM], alternatives=["fenrock-dragon-lords","darashia-dragon-lair"])

spot(id="carlin-cults", name="Carlin Cults", region="Carlin (podziemia)", continent="Tiquanda",
     city="Carlin", coords={"x":32340,"y":31790,"z":9,"approx":True},
     levelMin=90, levelMax=200, recLevel="90–180",
     vocations=["EK","RP","MS"],
     description="Podziemne tunele kultystów pod Carlin. Mocny exp, symboliczny profit — hunt typowo expowy.",
     stats=[stat("RP",90,1500000,50000), stat("MS",120,1600000,50000), stat("EK",90,1400000,50000,"estimate")],
     difficulty=4, risk=4, damageTypes=["physical","death"],
     monsters=[{"name":"Cult Enforcer","slug":"cult-enforcer"},{"name":"Cult Believer","slug":"cult-believer"},{"name":"Misguided Thief","slug":"cult-scholar"}],
     pulling="Duże grupy kultystów — używaj wejść jako choke pointów.",
     rotation="Główny tunel + odnoga zachodnia.",
     hero="carlin-cults.jpg", video={"title":"Carlin Cults (TibiaPal)","url":"https://youtu.be/iaFAdbZumZg"},
     sources=[TP], alternatives=["yalahar-cults","edron-heroes"])

spot(id="lizard-chosens", name="Lizard Chosens (okolice Banuty)", region="Tiquanda", continent="Tiquanda",
     city="Port Hope", coords={"x":32470,"y":32800,"z":8,"approx":True},
     levelMin=90, levelMax=180, recLevel="90–160",
     vocations=["EK","RP","MS"],
     description="Wybrańcy lisardów w kompleksie koło Banuty. Bardzo dobry exp dla 90–160, profit z ekwipunku chozenów.",
     stats=[stat("EK",130,1300000,250000,"estimate"), stat("RP",90,1400000,250000), stat("MS",120,1200000,200000)],
     difficulty=4, risk=4, damageTypes=["physical","earth","energy"],
     monsters=[{"name":"Lizard Chosen","slug":"lizard-chozarn"},{"name":"Lizard High Guardian","slug":"lizard-high-guardian"},{"name":"Lizard Legionnaire","slug":"lizard-legionnaire"}],
     resistances=["earth"],
     pulling="Choseni mają heal i summon — fokusuj ich pierwszym.",
     rotation="Sale główne, omijaj komnatę bossa.",
     hero=None, sources=[TP], alternatives=["muggy-plains","deeper-banuta"])

spot(id="edron-were-south", name="Edron South Werecreatures", region="Edron (południe)", continent="Edron",
     city="Edron", coords={"x":33186,"y":31916,"z":7,"approx":False},
     levelMin=90, levelMax=200, recLevel="90–180",
     vocations=["EK","RP","MS"],
     description="Lycantrophe Grounds na południe od Edronu (realny marker tibiamaps). Wereboary, werebeary i werewolfy — świetny exp + profit.",
     stats=[stat("RP",90,1550000,400000), stat("MS",100,1400000,550000), stat("EK",90,1450000,350000,"estimate")],
     difficulty=4, risk=4, damageTypes=["physical"],
     monsters=[{"name":"Wereboar","slug":"wereboar"},{"name":"Werebear","slug":"werebear"},{"name":"Werewolf","slug":"werewolf"}],
     pulling="Were-stwory są szybkie — trzymaj wąskie gardła.",
     rotation="Pętla po polanach, wycofanie do wąwozu.",
     hero="edron-were.jpg", video={"title":"Edron Were South (TibiaPal)","url":"https://youtu.be/bphN0gXwRdY"},
     sources=[TP,TM], alternatives=["grimvale-4","werehyaenas"])

spot(id="yielothax", name="Yielothax", region="Portal wymiarowy", continent="Tiquanda",
     city="—", coords={"x":32750,"y":32450,"z":9,"approx":True},
     levelMin=90, levelMax=140, recLevel="90–130",
     vocations=["EK","RP","MS"],
     description="Wymiarowe stwory Yielothax dostępne przez okresowe portale. Exp bez rewelacji profitowych, ciekawy przerywnik w grindzie.",
     stats=[stat("EK",90,900000,150000,"estimate"), stat("RP",90,950000,150000)],
     difficulty=3, risk=3, damageTypes=["physical","energy"],
     monsters=[{"name":"Yielothax","slug":"yielothax"}],
     bestTime="Portal pojawia się cyklicznie — sprawdź aktualny status w grze.",
     pulling="Yielothaxy teleportują — dobijaj szybko.",
     rotation="Krótka pętla wokół areny.",
     hero="yielothax.jpg", video={"title":"Yielothaxes (TibiaPal)","url":"https://youtu.be/-B50cMB2Ec4"},
     sources=[TP], alternatives=["exotic-cave","quaras-liberty-bay"])

spot(id="exotic-cave", name="Exotic Cave", region="Liberty Bay (okolice)", continent="Tiquanda",
     city="Liberty Bay", coords={"x":32350,"y":32830,"z":10,"approx":True},
     levelMin=90, levelMax=160, recLevel="90–150",
     vocations=["RP","EK","MS"],
     description="Jaskinia 'egzotycznych' stworów pod okolicami Liberty Bay. Wysoki exp i dobry profit dla 90+.",
     stats=[stat("RP",90,1500000,300000), stat("MS",100,1500000,200000)],
     difficulty=3, risk=3, damageTypes=["physical","fire","earth"],
     monsters=[{"name":"Chakoya Tribesman","slug":"chakoya-tribesman"},{"name":"Frost Giant","slug":"frost-giant"}],
     pulling="Mieszane obrażenia — miej uniwersalne resisty.",
     rotation="Pętla po trzech komorach.",
     hero="exotic.jpg", video={"title":"Exotic Cave (TibiaPal)","url":"https://youtu.be/vLgvvBAi1w4"},
     sources=[TP], alternatives=["yielothax","wyrms-liberty-bay"])

spot(id="grimvale-4", name="Grimvale –4", region="Grimvale", continent="Grimvale",
     city="Grimvale", coords={"x":33280,"y":31800,"z":11,"approx":True},
     levelMin=90, levelMax=180, recLevel="90–160",
     vocations=["EK","RP","MS"],
     description="Czwarte piętro dungeonu Grimvale (wyspa dostępna statkiem, marker tibiamaps). Mieszanka nieumarłych i were-stworów, bardzo dobry profit.",
     stats=[stat("RP",90,1300000,200000), stat("MS",100,1000000,500000), stat("EK",130,1200000,250000,"estimate")],
     difficulty=4, risk=4, damageTypes=["death","physical"],
     monsters=[{"name":"Werebadger","slug":"werebadger"},{"name":"Ghoul","slug":"ghoul"},{"name":"Crypt Shambler","slug":"crypt-shambler"}],
     resistances=["death"],
     access=["Statek do Grimvale (port w Edron / Yalahar zależnie od świata)"],
     pulling="–4 ma ciasne korytarze — idealne pod blocking EK.",
     rotation="Pętla po czterech salach piętra.",
     hero="grimvale.jpg", video={"title":"Grimvale -4 (TibiaPal)","url":"https://youtu.be/QIgtXAiPqBk"},
     sources=[TP,TM], alternatives=["edron-were-south","edron-vampire-crypt"])

spot(id="orlamond-west", name="Oramond West (Quara Raid)", region="Oramond", continent="Oramond",
     city="Oramond", coords={"x":33480,"y":32230,"z":8,"approx":True},
     levelMin=120, levelMax=220, recLevel="130–200",
     vocations=["EK","RP","MS"],
     description="Zachodnie tereny Oramondu z najazdami quar. Najlepszy wariant gdy aktywny jest raid quarowy — wyraźny skok expu.",
     stats=[stat("EK",130,1800000,150000,"estimate"), stat("RP",120,2300000,200000), stat("MS",150,2200000,300000)],
     difficulty=4, risk=4, damageTypes=["ice","physical"],
     monsters=[{"name":"Quara Predator","slug":"quara-predator"},{"name":"Quara Hydromancer","slug":"quara-hydromancer"},{"name":"Minotaur Hunter","slug":"minotaur-hunter"}],
     resistances=["ice"],
     bestTime="Najlepiej podczas aktywnego Quara raidu (world event).",
     pulling="Quary wychodzą falami — trzymaj się wzniesień.",
     rotation="Zachodnia pętla Oramondu od punktu startowego przy moście.",
     hero="orlamond-west.jpg", video={"title":"Oramond West Quara Raid (TibiaPal)","url":"https://youtu.be/kCxtakGFeDo"},
     sources=[TP], alternatives=["hydras-oramond","orlamond-minos"])

spot(id="yalahar-sunken-quarter", name="Yalahar Sunken Quarter (Quary)", region="Yalahar", continent="Zao",
     city="Yalahar", coords={"x":32790,"y":31270,"z":9,"approx":True},
     levelMin=100, levelMax=180, recLevel="130–170",
     vocations=["EK","RP","MS"],
     description="Zatopiona dzielnica Yalaharu pełna quar. Stabilny exp dla 130+, umiarkowany profit.",
     stats=[stat("EK",130,1400000,150000,"estimate"), stat("RP",90,1400000,150000), stat("MS",100,1250000,300000)],
     difficulty=4, risk=4, damageTypes=["ice","physical"],
     monsters=[{"name":"Quara Constrictor","slug":"quara-constrictor"},{"name":"Quara Mantassin","slug":"quara-mantaray"},{"name":"Quara Pincher","slug":"quara-pincher"}],
     resistances=["ice"],
     pulling="Pinchery paralyze'ują i mocno biją — priorytet celów.",
     rotation="Pętla po zatopionych ulicach dzielnicy.",
     hero="sunken-quarter.jpg", video={"title":"Sunken Quarter (TibiaPal)","url":"https://youtu.be/NFWBWpLU_v0"},
     sources=[TP], alternatives=["quaras-liberty-bay","orlamond-west"])

spot(id="okolnir", name="Okolnir Frost Dragons", region="Okolnir", continent="Svargrond",
     city="Svargrond", coords={"x":32230,"y":31080,"z":9,"approx":True},
     levelMin=130, levelMax=200, recLevel="130–180",
     vocations=["RP","MS","EK"],
     description="Lodowa wyspa Okolnir z frost dragonami. Bardzo dobry exp, lekki minus profitu — weź fire/ice resisty.",
     stats=[stat("RP",90,1300000,-100000), stat("MS",130,1300000,10000)],
     difficulty=4, risk=4, damageTypes=["ice"],
     monsters=[{"name":"Frost Dragon","slug":"frost-dragon"},{"name":"Ice Golem","slug":"ice-golem"}],
     resistances=["ice"],
     pulling="Frost dragony mają ice wave — nie stój w grupie.",
     rotation="Jaskinia główna bez zejścia do lodowych komór.",
     hero=None, sources=[TP], alternatives=["nibelor-crystal-spiders","sea-serpents"])

spot(id="souleater-mountain", name="Souleater Mountain", region="Góra Souleaterów", continent="Zao",
     city="—", coords={"x":32900,"y":31550,"z":8,"approx":True},
     levelMin=100, levelMax=160, recLevel="100–150",
     vocations=["RP","MS","EK"],
     description="Góra pełna souleaterów. Dobry exp i przyzwoity profit dla 100–150.",
     stats=[stat("RP",125,1250000,200000), stat("MS",100,1150000,350000)],
     difficulty=3, risk=3, damageTypes=["death"],
     monsters=[{"name":"Souleater","slug":"souleater"}],
     resistances=["death"],
     pulling="Souleatery lifedrainują — nie pozwól się otoczyć.",
     rotation="Pętla wokół szczytu.",
     hero="souleater.jpg", video={"title":"Souleater Mountain (TibiaPal)","url":"https://youtu.be/mmOYhUz4p5Y"},
     sources=[TP], alternatives=["yalahar-grim-reapers","drefia-grim-reapers"])

spot(id="hydras-oramond", name="Hydras Oramond", region="Oramond", continent="Oramond",
     city="Oramond", coords={"x":33510,"y":32250,"z":9,"approx":True},
     levelMin=130, levelMax=220, recLevel="130–200",
     vocations=["EK","RP","MS"],
     description="Legowisko hydr pod Oramondem. Klasyk dla EK z blockerem; hydry biją multi-atakami, więc party gra bezpiecznie.",
     stats=[stat("EK",130,1700000,200000,"estimate"), stat("RP",130,1500000,150000,"estimate")],
     dataQuality="estimate",
     difficulty=4, risk=4, damageTypes=["ice","physical","earth"],
     monsters=[{"name":"Hydra","slug":"hydra"}],
     resistances=["ice","earth"],
     modes=["solo","duo","party"], partyRec="EK blocker + ED healer + 1–2 DPS",
     pulling="Nie bij hydr na otwartej przestrzeni — 3 ataki naraz.",
     rotation="Komory hydr jedna po drugiej.",
     hero=None, sources=[TP], alternatives=["orlamond-west","deeper-banuta"])

spot(id="edron-orc-cults", name="Edron Orc Cults", region="Edron", continent="Edron",
     city="Edron", coords={"x":33140,"y":31770,"z":9,"approx":True},
     levelMin=100, levelMax=180, recLevel="130–170",
     vocations=["EK","RP","MS"],
     description="Jaskinia orkowych kultystów na Edronie. Dużo potworów, dobry exp dla EK; profit umiarkowany.",
     stats=[stat("EK",130,1150000,300000,"estimate"), stat("RP",90,1150000,300000)],
     difficulty=3, risk=3, damageTypes=["physical","death"],
     monsters=[{"name":"Orc Cultist","slug":"orc-cultist"},{"name":"Orc Berserker","slug":"orc-berserker"},{"name":"Orc Shaman","slug":"orc-shaman"}],
     pulling="Shamani summonują — zabijaj ich w pierwszej kolejności.",
     rotation="Główna sala + dwa korytarze.",
     hero=None, sources=[TP], alternatives=["edron-heroes","carlin-cults"])

spot(id="dark-faun-cave", name="Dark Faun Cave (Feyrist)", region="Feyrist", continent="Feyrist",
     city="—", coords={"x":33610,"y":31620,"z":9,"approx":True},
     levelMin=130, levelMax=220, recLevel="130–200",
     vocations=["EK","RP","MS"],
     description="Jaskinia mrocznych faunów w Feyrist. Dobry exp + profit, klimatyczny spawn dla 130+.",
     stats=[stat("EK",130,1100000,400000,"estimate"), stat("RP",90,950000,400000), stat("MS",130,1100000,400000)],
     difficulty=4, risk=4, damageTypes=["earth","physical"],
     monsters=[{"name":"Boogy","slug":"boogy"},{"name":"Pooka","slug":"pooka"},{"name":"Faun","slug":"pixie"}],
     resistances=["earth"],
     access=["Dostęp do Feyrist (quest Feyrist)"],
     pulling="Fauny rzucają klątwy — miej cleanse.",
     rotation="Pętla po jaskini centralnej.",
     hero="feyrist-surface.jpg", video={"title":"Dark Faun Cave / Feyrist (TibiaPal)","url":"https://youtu.be/Gl3JD_yjdOU"},
     sources=[TP], alternatives=["winter-court","grimvale-4"])

spot(id="ravenous-lava-lurkers", name="Ravenous Lava Lurkers", region="Podziemne tereny lawy", continent="Zao",
     city="Rathleton", coords={"x":33560,"y":31900,"z":10,"approx":True},
     levelMin=100, levelMax=180, recLevel="100–160",
     vocations=["RP","EK","MS"],
     description="Żarłoczne lawowe stwory — bardzo wysoki exp z lekkim minusem profitu. Miejsce dla fanów czystego grindowania.",
     stats=[stat("RP",100,2100000,-50000), stat("MS",100,1600000,-200000)],
     difficulty=4, risk=4, damageTypes=["fire"],
     monsters=[{"name":"Lava Lurker","slug":"fire-elemental"},{"name":"Hellfire Fighter","slug":"hellfire-fighter"}],
     resistances=["fire"],
     pulling="Stwory zostawiają pola ognia — ruszaj się cały czas.",
     rotation="Pętla po lawowych komnatach.",
     hero="ravenous.jpg", video={"title":"Ravenous Lava Lurkers (TibiaPal)","url":"https://youtu.be/dFqQ8lPenh4"},
     sources=[TP], alternatives=["glooth-tower","orlamond-west"])

spot(id="putrid-mummy", name="Putrid Mummy", region="Darama (grobowce)", continent="Darama",
     city="Ankrahmun", coords={"x":33150,"y":32800,"z":10,"approx":True},
     levelMin=90, levelMax=140, recLevel="90–130",
     vocations=["RP","MS","EK"],
     description="Spawn zgniłych mumii w grobowcach Daramy. Wyróżnia się rewelacyjnym profitem przy solidnym expie.",
     stats=[stat("RP",90,700000,700000), stat("MS",90,700000,500000)],
     difficulty=3, risk=3, damageTypes=["death","earth"],
     monsters=[{"name":"Putrid Mummy","slug":"mummy"}],
     resistances=["death","earth"],
     pulling="Mumie trują i drenują — trzymaj dystans.",
     rotation="Krótka, gęsta pętla po kryptach.",
     hero=None, sources=[TP], alternatives=["mosl-3","drefia-grim-reapers"])

spot(id="peninsula-tomb", name="Peninsula Tomb", region="Darama", continent="Darama",
     city="Ankrahmun", coords={"x":33170,"y":32870,"z":10,"approx":True},
     levelMin=55, levelMax=90, recLevel="60–85",
     vocations=["RP","MS"],
     description="Grobowiec na półwyspie koło Ankrahmun. Klasyczny hunt 60–85 z klimatem starych krypt.",
     stats=[stat("RP",60,400000,20000), stat("MS",55,420000,20000)],
     difficulty=3, risk=3, damageTypes=["death","physical"],
     monsters=[{"name":"Mummy","slug":"mummy"},{"name":"Bonebeast","slug":"demon-skeleton"}],
     resistances=["death"],
     pulling="Ciasne pokoje — pulluj pojedynczo.",
     rotation="Pętla po piętrach grobowca.",
     hero="peninsula-tomb.jpg", video={"title":"Peninsula Tomb (TibiaPal)","url":"https://youtu.be/vZDF-hfTdbU"},
     sources=[TP], alternatives=["mosl-3","putrid-mummy"])

spot(id="iksupan", name="Iksupan", region="Kraina Iks", continent="Kilmaresh",
     city="Kilmaresh", coords={"x":33800,"y":31500,"z":9,"approx":True},
     levelMin=70, levelMax=150, recLevel="70–140",
     vocations=["RP","MS","EK"],
     description="Podziemne miasto Iks (Iksupan) — świetny exp i profit dla 70–140. Wymaga dostępu z questa Kilmaresh/Iks.",
     stats=[stat("RP",70,950000,200000), stat("MS",80,1050000,400000)],
     quests=["Dostęp do Iksupan (questy Kilmaresh)"],
     difficulty=3, risk=3, damageTypes=["physical","earth"],
     monsters=[{"name":"Iks lizards","slug":"lizard-magistratus"},{"name":"Iks skirmishers","slug":"lizard-legionnaire"}],
     pulling="Grupy jaszczurów trzymają szyk — rozbijaj je falami.",
     rotation="Górne sale miasta, bez schodzenia do sanktuarium.",
     hero="iksupan.jpg", video={"title":"Iksupan (TibiaPal)","url":"https://youtu.be/OWJwEEbih9g"},
     sources=[TP], alternatives=["iksupan-last-stand","issavi-crypts"])

spot(id="old-masonry", name="Old Masonry (Death Portal)", region="Edron (okolice)", continent="Edron",
     city="Edron", coords={"x":33160,"y":31860,"z":9,"approx":True},
     levelMin=90, levelMax=150, recLevel="90–140",
     vocations=["RP","MS"],
     description="Stare mury z portalem śmierci — nieumarli o wysokiej gęstości. Dobry exp, niski profit.",
     stats=[stat("RP",90,1050000,100000), stat("MS",80,825000,80000)],
     difficulty=3, risk=3, damageTypes=["death"],
     monsters=[{"name":"Undead Dragon","slug":"ghastly-dragon"},{"name":"Skeleton Elite","slug":"skeleton"}],
     resistances=["death"],
     pulling="Portal spawnuje fale — kontroluj tempo.",
     rotation="Jedna pętla wokół ruin.",
     hero="old-masonry.jpg", video={"title":"Old Masonry Death portal (TibiaPal)","url":"https://youtu.be/Ydlh73-uzAU"},
     sources=[TP], alternatives=["edron-heroes","yalahar-grim-reapers"])

spot(id="holy-portal", name="Holy Portal", region="Darama", continent="Darama",
     city="Darashia", coords={"x":33100,"y":32480,"z":9,"approx":True},
     levelMin=90, levelMax=140, recLevel="90–130",
     vocations=["RP","MS"],
     description="Portal świętości z niebiańskimi stworami. Bardzo dobry profit, przyzwoity exp — niedoceniany hunt 90+.",
     stats=[stat("RP",90,1100000,400000), stat("MS",120,1300000,900000)],
     difficulty=3, risk=3, damageTypes=["holy"],
     monsters=[{"name":"Holy creatures","slug":"hero"}],
     resistances=["holy"],
     pulling="Stwory biją holy — holy protection rzadko pomaga, licz na HP.",
     rotation="Krótka pętla przy portalu.",
     hero="holy-portal.jpg", video={"title":"Holy Portal (TibiaPal)","url":"https://youtu.be/jVwW9hs7oRA"},
     sources=[TP], alternatives=["lions-rock","putrid-mummy"])

spot(id="krailos-nightmare-scions", name="Nightmare Scions Krailos", region="Krailos", continent="Krailos",
     city="Krailos", coords={"x":32290,"y":31880,"z":9,"approx":True},
     levelMin=90, levelMax=150, recLevel="90–140",
     vocations=["EK","RP","MS"],
     description="Koszmarne źrebięta w jaskiniach Krailos. Dobry exp dla 90+, niski profit.",
     stats=[stat("EK",90,1100000,100000,"estimate"), stat("RP",90,1200000,100000)],
     difficulty=3, risk=3, damageTypes=["death"],
     monsters=[{"name":"Nightmare Scion","slug":"nightmare-scion"}],
     resistances=["death"],
     pulling="Sciony są szybkie — pulluj na korytarz.",
     rotation="Pętla po dwóch komorach.",
     hero=None, sources=[TP], alternatives=["krailos-bug-cave","yalahar-grim-reapers"])

# ================================================================ 150-300
spot(id="deeplings-library", name="Deeplings Library", region="Podwodna biblioteka", continent="Tiquanda",
     city="—", coords={"x":32330,"y":32850,"z":11,"approx":True},
     levelMin=120, levelMax=250, recLevel="130–220",
     vocations=["EK","RP","MS"],
     description="Biblioteka deeplingów — jeden z najlepszych profitowych huntów 130–220. Wysoki exp + bardzo dobry loot.",
     stats=[stat("EK",185,1500000,800000,"estimate"), stat("RP",120,1600000,800000), stat("MS",150,1500000,800000)],
     difficulty=4, risk=4, damageTypes=["ice","physical"],
     monsters=[{"name":"Deepling Master Librarian","slug":"deepling-master-librarian"},{"name":"Deepling Elite","slug":"deepling-elite"},{"name":"Deepling Warrior","slug":"deepling-warrior"}],
     resistances=["ice"],
     access=["Sprzęt do nurkowania + dostęp do biblioteki (quest)"],
     pulling="Librarian rzuca silne zaklęcia — cisza/fokus na niego.",
     rotation="Sala główna biblioteki, bez archiwum na 120–150 lv.",
     hero=None, sources=[TP], alternatives=["seacrest-serpents","quaras-liberty-bay"])

spot(id="yalahar-grim-reapers", name="Yalahar Grim Reapers", region="Yalahar (cmentarzysko)", continent="Zao",
     city="Yalahar", coords={"x":32750,"y":31290,"z":9,"approx":True},
     levelMin=150, levelMax=350, recLevel="200–320",
     vocations=["EK","RP","MS"],
     description="Żniwiarze pod Yalaharem — kultowy, bardzo expowy spawn 200+. Profit ujemny: nastaw się na koszty potionów.",
     stats=[stat("EK",200,3000000,-100000,"estimate"), stat("RP",150,2750000,-400000), stat("RP",200,3400000,-200000), stat("MS",200,3200000,-50000)],
     difficulty=4, risk=5, damageTypes=["death"],
     monsters=[{"name":"Grim Reaper","slug":"grim-reaper"}],
     resistances=["death"],
     pulling="Reapery teleportują i biją death wave — nie stój plecami do ściany.",
     rotation="Pętla po katakumbach, wycofanie przez kaplicę.",
     hero="yalahar-gr.jpg", video={"title":"Yalahar Grim Reapers (TibiaPal)","url":"https://youtu.be/7n6z0B-G0oE"},
     sources=[TP], alternatives=["drefia-grim-reapers","nightmare-isles"])

spot(id="werehyaenas", name="Werehyaenas (South/North)", region="Okolice Grimvale", continent="Grimvale",
     city="Grimvale", coords={"x":33290,"y":31740,"z":9,"approx":True},
     levelMin=200, levelMax=400, recLevel="200–350",
     vocations=["EK","RP","MS"],
     description="Południowe i północne legowiska werehyen. Topowy hunt 200–350 z dobrym expem i profit; ice resist kluczowy.",
     stats=[stat("EK",200,2600000,300000,"estimate"), stat("RP",90,850000,10000), stat("RP",200,3100000,300000), stat("MS",200,2600000,400000)],
     difficulty=4, risk=4, damageTypes=["physical","ice"],
     monsters=[{"name":"Werehyaena","slug":"werehyaena"}],
     resistances=["ice"],
     pulling="Hyeny wyją i wzmacniają się nawzajem — rozbijaj grupy.",
     rotation="South dla 200–280, North od 280+.",
     hero="werehyaenas-s.jpg", video={"title":"Werehyaenas South (TibiaPal)","url":"https://youtu.be/7UTofKsb-Kk"},
     sources=[TP], alternatives=["edron-were-south","weretigers"])

spot(id="seacrest-serpents", name="Seacrest Serpents (Birthing Grounds)", region="Morze koło Oramond", continent="Oramond",
     city="Oramond", coords={"x":33460,"y":32260,"z":10,"approx":True},
     levelMin=200, levelMax=350, recLevel="200–320",
     vocations=["EK","RP","MS"],
     description="Podwodne tarlisko seacrest serpentów. Dobry exp i profit dla 200+, wymaga sprzętu do nurkowania.",
     stats=[stat("EK",200,2200000,300000,"estimate"), stat("RP",200,2200000,350000), stat("MS",200,2100000,300000)],
     difficulty=4, risk=4, damageTypes=["ice","energy"],
     monsters=[{"name":"Seacrest Serpent","slug":"sea-serpent"}],
     resistances=["ice","energy"],
     pulling="Węże falują atakami — trzymaj pionowe korytarze.",
     rotation="Pętla po tarlisku.",
     hero=None, sources=[TP], alternatives=["deeplings-library","hydras-oramond"])

spot(id="glooth-tower", name="Glooth Tower", region="Rathleton (okolice)", continent="Zao",
     city="Rathleton", coords={"x":33563,"y":31916,"z":7,"approx":False},
     levelMin=150, levelMax=300, recLevel="150–280",
     vocations=["RP","EK","MS"],
     description="Wieża glooth koło Rathleton (realny marker tibiamaps). Solidny exp i profit dla 150+, część mechanik z questa Glooth.",
     stats=[stat("RP",150,2100000,400000), stat("EK",150,2000000,400000,"estimate")],
     difficulty=4, risk=4, damageTypes=["energy","physical","earth"],
     monsters=[{"name":"Glooth Bandit","slug":"glooth-bandit"},{"name":"Glooth Brigand","slug":"glooth-brigand"},{"name":"Glooth Golem","slug":"glooth-golem"}],
     resistances=["energy"],
     quests=["Dostęp do wieży (Glooth quest)"],
     pulling="Bandyci używają broni dystansowej — zasłony.",
     rotation="Piętra wieży od dołu.",
     hero="glooth-bandits.jpg", video={"title":"Glooth Bandits (TibiaPal)","url":"https://youtu.be/jAbq6eP8Sag"},
     sources=[TP,TM], alternatives=["ravenous-lava-lurkers","draken-walls"])

spot(id="draken-walls", name="Draken Walls", region="Zao / Krailos", continent="Zao",
     city="—", coords={"x":33750,"y":31700,"z":8,"approx":True},
     levelMin=200, levelMax=350, recLevel="200–320",
     vocations=["EK","RP","MS"],
     description="Mury drakenów — gęsty spawn wojowników i magów draken. Wysoki exp, bardzo dobry profit z lootu.",
     stats=[stat("EK",200,2700000,700000,"estimate"), stat("RP",200,2800000,750000)],
     difficulty=4, risk=4, damageTypes=["physical","ice","energy"],
     monsters=[{"name":"Draken Spellweaver","slug":"draken-spellweaver"},{"name":"Draken Warmaster","slug":"draken-warmaster"},{"name":"Draken Abomination","slug":"draken-abomination"}],
     resistances=["physical","energy"],
     pulling="Spellweaverzy z distance — zamykaj korytarze runami.",
     rotation="Pętla po murach zewnętrznych.",
     hero=None, sources=[TP], alternatives=["hive-surface","lizard-chosens"])

spot(id="orlamond-minos", name="Oramond Minotaurs (South)", region="Oramond", continent="Oramond",
     city="Oramond", coords={"x":33500,"y":32260,"z":8,"approx":True},
     levelMin=150, levelMax=260, recLevel="150–240",
     vocations=["EK","RP","MS"],
     description="Południowe tereny Oramondu z minotaurami (amazonki, invaderzy, moohtanty). Dobry exp i profit dla 150+.",
     stats=[stat("EK",150,1500000,150000,"estimate"), stat("RP",90,1300000,100000)],
     difficulty=4, risk=4, damageTypes=["physical","energy"],
     monsters=[{"name":"Minotaur Amazon","slug":"minotaur-amazon"},{"name":"Minotaur Invader","slug":"minotaur-invader"},{"name":"Moohtant","slug":"moohtant"},{"name":"Execowtioner","slug":"execowtioner"}],
     pulling="Execowtionerzy biją area — rozpraszaj grupy.",
     rotation="Łąki południowe od mostu Oramond.",
     hero=None, sources=[TP], alternatives=["orlamond-west","hydras-oramond"])

spot(id="medusa-tower", name="Medusa Tower", region="Okolice Ankrahmun", continent="Darama",
     city="Ankrahmun", coords={"x":32853,"y":32814,"z":7,"approx":False},
     levelMin=200, levelMax=400, recLevel="250–380",
     vocations=["EK","RP","MS"],
     description="Wieża meduz (realny marker 'Medusa Tower entrance'). Topowy hunt 250+ — energy resist i szybkie zabijanie meduz obowiązkowe.",
     stats=[stat("EK",250,2600000,100000,"estimate"), stat("RP",200,2600000,100000), stat("MS",275,2700000,250000)],
     difficulty=5, risk=5, damageTypes=["earth","energy"],
     monsters=[{"name":"Medusa","slug":"medusa"}],
     resistances=["earth","energy"],
     pulling="Nie patrz meduzie 'w oczy' gdy castuje — odwracaj/uciekaj.",
     rotation="Piętra wieży pojedynczo.",
     hero="medusa-tower.jpg", video={"title":"Medusa Tower (TibiaPal)","url":"https://youtu.be/QlUzYWmsIP8"},
     sources=[TP,TM], alternatives=["deeper-banuta","asura-palace"])

spot(id="asura-palace", name="Asura Palace", region="Yalahar (okolice)", continent="Zao",
     city="Yalahar", coords={"x":32948,"y":32689,"z":7,"approx":False},
     levelMin=200, levelMax=400, recLevel="250–380",
     vocations=["EK","RP","MS"],
     description="Pałac asur (realny marker tibiamaps). Jeden z najpopularniejszych huntów 250–400 dla każdej profesji.",
     stats=[stat("EK",200,3000000,300000,"estimate"), stat("RP",200,3100000,100000), stat("MS",275,3100000,500000)],
     difficulty=4, risk=4, damageTypes=["energy","fire","death"],
     monsters=[{"name":"Asura","slug":"asura"},{"name":"Dawnfire Asura","slug":"dawnfire-asura"},{"name":"Frost Flower Asura","slug":"frost-flower-asura"},{"name":"Midnight Asura","slug":"midnight-asura"}],
     resistances=["energy"],
     pulling="Asury teleportują i rzucają beamy — trzymaj filary.",
     rotation="Sale pałacu od wejścia, mirror dla 350+.",
     hero=None, sources=[TP,TM], alternatives=["asura-mirror","medusa-tower"])

spot(id="deeper-banuta", name="Deeper Banuta", region="Banuta", continent="Tiquanda",
     city="Port Hope", coords={"x":32450,"y":32790,"z":10,"approx":True},
     levelMin=200, levelMax=450, recLevel="300–420",
     vocations=["EK","RP","MS"],
     description="Głęboka Banuta: meduzy, serpent spawny, phantasmy i ghastle. Klasyk dla EK 300+ (Intibia: 2.2–4kk exp, 250–700k profit).",
     stats=[stat("EK",300,3100000,475000), stat("RP",200,2600000,300000), stat("MS",300,2700000,250000)],
     quests=["The Ape City Quest — misja 'The Catacombs' (skrót)"],
     difficulty=5, risk=5, damageTypes=["earth","death","physical"],
     monsters=[{"name":"Medusa","slug":"medusa"},{"name":"Serpent Spawn","slug":"serpent-spawn"},{"name":"Phantasm","slug":"phantasm"},{"name":"Ghastly Dragon","slug":"ghastly-dragon"},{"name":"Hellspawn","slug":"hellspawn"},{"name":"Hydra","slug":"hydra"}],
     resistances=["earth","death"],
     access=["Rope; Premium Account"],
     runes=["Icicle / Avalanche"],
     pulling="–4: pulluj meduzy pojedynczo na korytarz; energy/fire bronie najlepsze.",
     rotation="Piętra –4/–6/–8 zależnie od levelu; –8 od 300+.",
     hero="deeper-banuta.jpg", video={"title":"Deeper Banuta Bottom Floor | 3.1kk/h | 300+ Knight (Intibia)","url":"https://www.youtube.com/watch?v=C3HBF3noWV0"},
     sources=[TP,IN], alternatives=["medusa-tower","lizard-chosens"])

spot(id="drefia-grim-reapers", name="Drefia Grim Reapers", region="Drefia", continent="Darama",
     city="Darashia", coords={"x":33150,"y":32530,"z":9,"approx":True},
     levelMin=200, levelMax=400, recLevel="300–380",
     vocations=["EK","RP","MS"],
     description="Nekropolia Drefia ze żniwiarzami. Wysoki exp, ujemny profit — miejsce dla łowców leveli.",
     stats=[stat("EK",150,2000000,-150000,"estimate"), stat("RP",200,2200000,-250000)],
     difficulty=4, risk=5, damageTypes=["death","fire"],
     monsters=[{"name":"Grim Reaper","slug":"grim-reaper"},{"name":"Elder Wyrm","slug":"elder-wyrm"}],
     resistances=["death"],
     pulling="Reapery w Drefii są gęstsze niż w Yalahar — uważaj.",
     rotation="Katakumby Drefii od wschodu.",
     hero=None, sources=[TP], alternatives=["yalahar-grim-reapers","souleater-mountain"])

spot(id="lower-spike", name="Lower Spike", region="The Spike", continent="Tiquanda",
     city="Ab'Dendriel", coords={"x":32624,"y":31854,"z":13,"approx":False},
     levelMin=250, levelMax=400, recLevel="275–380",
     vocations=["RP","EK","MNK"],
     description="Najniższe pietra The Spike — endgame'owa wersja questa dla 275+. Bardzo wysoki exp i świetny profit.",
     stats=[stat("RP",275,3200000,1500000), stat("EK",250,3000000,1200000,"estimate")],
     quests=["The Spike Quest (ukończone wyższe pietra)"],
     difficulty=5, risk=5, damageTypes=["physical","energy"],
     monsters=[{"name":"Spikes creatures","slug":"walker"},{"name":"Lost Husher","slug":"lost-husher"}],
     pulling="Fale potworów przy taskach — pełne potiony i runy.",
     rotation="Taski dolnych pięter po kolei.",
     hero="lower-spike.jpg", video={"title":"Lower Spike (TibiaPal)","url":"https://youtu.be/C0DxJu8bt5A"},
     sources=[TP,TM], alternatives=["middle-spike","gnome-warzones"])

spot(id="gnome-warzones", name="Warzone 4/5/6 (Gnome Deep)", region="Gnome Deep", continent="Krailos",
     city="—", coords={"x":32280,"y":31920,"z":12,"approx":True},
     levelMin=230, levelMax=450, recLevel="250–400",
     vocations=["RP","EK","MS"],
     description="Strefy wojenne krasnoludów (Warzones 4–6). Topowy exp dla 250–400, bardzo dobry profit z tasków i lootu.",
     stats=[stat("RP",230,4300000,800000), stat("MS",275,4300000,900000), stat("EK",230,3900000,700000,"estimate")],
     quests=["Dostęp do Warzones (Gnome Deep questy)"],
     difficulty=5, risk=5, damageTypes=["fire","physical","energy"],
     monsters=[{"name":"Warzone creatures","slug":"glooth-golem"},{"name":"Lost Basher","slug":"lost-basher"}],
     modes=["solo","duo","party"], partyRec="2–4 osoby; EK + ED + DPS",
     pulling="Każda warzone ma inną mechanikę — poznaj bezpieczne rogi.",
     rotation="WZ5 dla 230–320, WZ4/WZ6 od 300+.",
     hero="warzone5.jpg", video={"title":"Warzone 5 (TibiaPal)","url":"https://youtu.be/nT4JTCqTGlw"},
     sources=[TP], alternatives=["lower-spike","asura-mirror"])

spot(id="asura-mirror", name="Asura Mirror", region="Yalahar (okolice)", continent="Zao",
     city="Yalahar", coords={"x":32953,"y":32668,"z":9,"approx":False},
     levelMin=300, levelMax=500, recLevel="350–480",
     vocations=["EK","RP","MS"],
     description="Lustrzane piętro pałacu asur (realny marker tibiamaps). EK: 4–6kk/h (Intibia 400+), RP: 5.3kk/h — ścisła czołówka 350+.",
     stats=[stat("EK",400,5000000,650000), stat("RP",250,5300000,600000), stat("MS",300,4400000,400000)],
     difficulty=5, risk=5, damageTypes=["energy","fire","ice"],
     monsters=[{"name":"True Midnight Asura","slug":"true-midnight-asura"},{"name":"True Dawnfire Asura","slug":"true-dawnfire-asura"},{"name":"True Frost Flower Asura","slug":"true-frost-flower-asura"}],
     resistances=["energy"],
     pulling="True asury mają beamy przez ściany — pilnuj linii.",
     rotation="–1 lustra od wejścia głównego.",
     hero="asura-mirror.jpg", video={"title":"Asura Mirror (TibiaPal)","url":"https://youtu.be/MLXqo7TUBB0"},
     sources=[TP,IN,TM], alternatives=["asura-palace","true-asuras"])

spot(id="lower-roshamuul", name="Lower Roshamuul", region="Roshamuul", continent="Roshamuul",
     city="Roshamuul", coords={"x":33650,"y":32400,"z":9,"approx":True},
     levelMin=350, levelMax=600, recLevel="350–550",
     vocations=["EK","RP","MS"],
     description="Dolne partie wyspy Roshamuul: guzzlemawy, silencers i terrorsleepy. Wysoki exp i profit dla 350+.",
     stats=[stat("EK",350,3300000,400000,"estimate"), stat("RP",230,3400000,400000)],
     difficulty=5, risk=5, damageTypes=["physical","death"],
     monsters=[{"name":"Guzzlemaw","slug":"guzzlemaw"},{"name":"Silencer","slug":"silencer"},{"name":"Terrorsleep","slug":"terrorsleep"}],
     resistances=["physical"],
     pulling="Guzzlemawy pożerają fieldy — ruszaj się.",
     rotation="Pętla po dolnych ruinach.",
     hero="upper-rosh.jpg", video={"title":"Roshamuul (TibiaPal)","url":"https://youtu.be/f75JLZgI6sI"},
     sources=[TP], alternatives=["roshamuul-prison","weretigers"])

spot(id="roshamuul-prison", name="Roshamuul Prison –1", region="Roshamuul", continent="Roshamuul",
     city="Roshamuul", coords={"x":33589,"y":32432,"z":7,"approx":False},
     levelMin=400, levelMax=700, recLevel="500–650",
     vocations=["EK","RP","MS"],
     description="Więzienie Roshamuul (realny marker tibiamaps). EK 500+: 2.8–3.5kk exp, 600–900k profit (Intibia). Demony, juggernauty i blightwalkerzy.",
     stats=[stat("EK",500,3150000,750000), stat("RP",400,3200000,600000,"estimate")],
     difficulty=5, risk=5, damageTypes=["physical","fire","death"],
     monsters=[{"name":"Demon","slug":"demon"},{"name":"Demon Outcast","slug":"demon-outcast"},{"name":"Juggernaut","slug":"juggernaut"},{"name":"Blightwalker","slug":"blightwalker"}],
     resistances=["physical","death"],
     access=["Dostęp do Roshamuul (quest)"],
     pulling="–1: pulluj na schody, outcastów kasuj pierwszymi.",
     rotation="Korytarz główny + cele wschodnie.",
     hero=None, sources=[IN,TM], alternatives=["lower-roshamuul","ferumbras-seals"])

spot(id="winter-court", name="Winter Court (Feyrist)", region="Feyrist", continent="Feyrist",
     city="—", coords={"x":33600,"y":31600,"z":7,"approx":True},
     levelMin=300, levelMax=600, recLevel="350–550",
     vocations=["MS","RP","EK","ED"],
     description="Zimowy dwór w Feyrist: crazed winter vanguards i thanatursusy. MS/RP: 4.4–5.6kk/h. Wymaga dostępu do Feyrist.",
     stats=[stat("MS",275,4400000,1000000), stat("RP",300,4400000,500000), stat("MS",400,5600000,1000000)],
     quests=["Dostęp do Feyrist"],
     difficulty=5, risk=5, damageTypes=["ice","physical"],
     monsters=[{"name":"Crazed Winter Vanguard","slug":"crazed-winter-vanguard"},{"name":"Soul-Broken Harbinger","slug":"soul-broken-harbinger"},{"name":"Thanatursus","slug":"thanatursus"}],
     resistances=["ice"],
     pulling="Vanguardi mają ice burst — trzymaj dystans magami.",
     rotation="Zamek dworu (castle only) dla 300–400, pełna pętla od 400+.",
     hero="winter-court-full.jpg", video={"title":"Winter Court Full Lap (TibiaPal)","url":"https://youtu.be/QogiVuDvoWo"},
     sources=[TP], alternatives=["summer-court","dark-faun-cave"])

spot(id="summer-court", name="Summer Court (Feyrist)", region="Feyrist", continent="Feyrist",
     city="—", coords={"x":33620,"y":31580,"z":7,"approx":True},
     levelMin=450, levelMax=800, recLevel="450–700",
     vocations=["MS","RP","EK"],
     description="Letni dwór Feyrist — hunt 450+ o bardzo wysokiej gęstości. MS: 5kk+, świetny loot z fae-stworów.",
     stats=[stat("RP",300,5000000,800000), stat("MS",400,5200000,800000)],
     quests=["Dostęp do Feyrist"],
     difficulty=5, risk=5, damageTypes=["fire","earth","holy"],
     monsters=[{"name":"Carnisylvan","slug":"pixie"},{"name":"Feyrist court creatures","slug":"boogy"}],
     resistances=["fire","earth"],
     pulling="Mieszane dmg — pełne resist sety.",
     rotation="Half boxes dla 450–550, full boxing od 550+.",
     hero="summer-court.jpg", video={"title":"Summer Court (TibiaPal)","url":"https://youtu.be/C90I0c20dI4"},
     sources=[TP], alternatives=["winter-court","cobra-bastion"])

spot(id="flimsy-lost-souls", name="Flimsy Lost Souls (Venore / Port Hope)", region="Okolice Venore i Port Hope", continent="Tiquanda",
     city="Venore", coords={"x":32860,"y":32100,"z":9,"approx":True},
     levelMin=400, levelMax=800, recLevel="400–700",
     vocations=["RP","MS","EK"],
     description="Legowiska flimsy lost souls pod Venore i Port Hope. RP: 5.5–6kk/h (–1), MS nawet 8kk+ przy -1/-2. Endgame'owy exp.",
     stats=[stat("RP",400,6000000,1000000), stat("MS",500,8100000,1000000)],
     difficulty=5, risk=5, damageTypes=["death","earth"],
     monsters=[{"name":"Flimsy Lost Soul","slug":"flimsy-lost-soul"},{"name":"Mean Lost Soul","slug":"mean-lost-soul"},{"name":"Freakish Lost Soul","slug":"freakish-lost-soul"}],
     resistances=["death","earth"],
     pulling="Dusze drenują manę i HP — exura na cooldownie.",
     rotation="Tylko piętro –1 dla 400–500, –2 od 500+.",
     hero="flimsy-venore.jpg", video={"title":"Flimsy Venore -1/-2 (TibiaPal)","url":"https://youtu.be/0QEozjzblv0"},
     sources=[TP], alternatives=["netherworld","cobra-bastion"])

spot(id="cobra-bastion", name="Cobra Bastion", region="Darama (zachód)", continent="Darama",
     city="Darashia", coords={"x":33314,"y":32647,"z":7,"approx":False},
     levelMin=500, levelMax=1000, recLevel="500–900",
     vocations=["RP","MS","EK"],
     description="Bastion kobr (realny marker 'To Cobra Bastion'). RP: 7.2kk/h, MS: 7.5kk/h. Endgame dla 500+ z bogatym lootem.",
     stats=[stat("RP",500,7200000,1200000), stat("MS",600,7500000,800000)],
     difficulty=5, risk=5, damageTypes=["earth","fire","energy","death"],
     monsters=[{"name":"Cobra","slug":"cobra"},{"name":"Cobra Scout","slug":"cobra-scout"},{"name":"Cobra Assassin","slug":"cobra-assassin"},{"name":"Cobra Vizier","slug":"cobra-vizier"},{"name":"Bashmu","slug":"bashmu"}],
     resistances=["earth","energy"],
     access=["Dostęp do Cobra Bastion (quest)"],
     pulling="Bastion ma zasadzki — sprawdzaj rogi przed wejściem.",
     rotation="Parter dla 500–600, basement –1 od 600+.",
     hero="cobra-bastion.jpg", video={"title":"Cobra Bastion (TibiaPal)","url":"https://youtu.be/0zXYigzxGTA"},
     sources=[TP,TM], alternatives=["issavi-crypts","ferumbras-seals"])

spot(id="issavi-crypts", name="Issavi Crypts (Sphinx / Crypt Wardens)", region="Kilmaresh / Issavi", continent="Kilmaresh",
     city="Issavi", coords={"x":33920,"y":31480,"z":8,"approx":False},
     levelMin=400, levelMax=750, recLevel="400–700",
     vocations=["MS","RP","EK"],
     description="Krypty Issavi ze sfinksami i strażnikami (realny marker depotu Issavi). MS: do 7kk/h. Death damage dominuje.",
     stats=[stat("MS",500,7000000,1200000), stat("RP",600,6500000,1000000)],
     difficulty=5, risk=5, damageTypes=["death","physical"],
     monsters=[{"name":"Feral Sphinx","slug":"feral-sphinx"},{"name":"Sphinx","slug":"sphinx"},{"name":"Lamassu","slug":"lamassu"},{"name":"Crypt Warden","slug":"crypt-warden"}],
     resistances=["death"],
     pulling="Warden ma mocny melee — EK musi trzymać aggro.",
     rotation="Krypty centralne, bez zachodniego skrzydła poniżej 500 lv.",
     hero="issavi-sphinxes.jpg", video={"title":"Issavi Sphinxes & Crypt Wardens (TibiaPal)","url":"https://youtu.be/Hqz9qG58_EU"},
     sources=[TP,TM], alternatives=["issavi-goannas","cobra-bastion"])

spot(id="issavi-goannas", name="Issavi Goannas (Central Steppe)", region="Kilmaresh", continent="Kilmaresh",
     city="Issavi", coords={"x":33880,"y":31520,"z":7,"approx":True},
     levelMin=500, levelMax=900, recLevel="500–800",
     vocations=["MS","EK","RP"],
     description="Centralny step Kilmaresh z goannami (Intibia: ED/MS 700+ 8–20kk/h w party). Powierzchniowy hunt o ogromnym expie.",
     stats=[stat("MS",500,6300000,1300000), stat("ED",700,12000000,1000000,"estimate")],
     difficulty=5, risk=5, damageTypes=["earth","physical"],
     monsters=[{"name":"Goanna","slug":"lizard-high-guardian"}],
     resistances=["earth"],
     modes=["solo","duo","party"], partyRec="ED/MS area dmg; najlepiej 2–4 osoby",
     pulling="Goanny są rozproszone — area spellami po grupach.",
     rotation="Step centralny od wejścia przy katakumbach.",
     hero="issavi-goannas.jpg", video={"title":"Issavi Goannas (TibiaPal)","url":"https://youtu.be/OS8Suk7xFno"},
     sources=[TP,IN], alternatives=["issavi-crypts","cobra-bastion"])

spot(id="nightmare-isles", name="Nightmare Isles", region="Okolice Yalahar", continent="Zao",
     city="Yalahar", coords={"x":32700,"y":31350,"z":8,"approx":True},
     levelMin=400, levelMax=700, recLevel="500–650",
     vocations=["EK","RP","MS"],
     description="Wyspy koszmarów — gęsty spawn nightmare'ów dla 500+. Wysoki exp, dostęp przez quest.",
     stats=[stat("EK",500,4000000,300000,"estimate"), stat("RP",500,4200000,300000,"estimate")],
     dataQuality="estimate",
     difficulty=5, risk=5, damageTypes=["death","physical"],
     monsters=[{"name":"Nightmare","slug":"nightmare"},{"name":"Nightmare Scion","slug":"nightmare-scion"}],
     resistances=["death"],
     pulling="Nightmare'y paralyze'ują i teleportują.",
     rotation="Wyspy po kolei mostami.",
     hero=None, sources=[TP], alternatives=["yalahar-grim-reapers","asura-mirror"])

spot(id="book-world", name="Book World (Chapter II–IV)", region="Biblioteka wymiarów", continent="Zao",
     city="—", coords={"x":32177,"y":31925,"z":8,"approx":True},
     levelMin=200, levelMax=450, recLevel="200–400",
     vocations=["RP","EK","MS"],
     description="Książkowe światy z questa The Secret Library (marker tibiamaps). Chapter III: RP 3.9kk/h. Klimatyczny i bardzo expowy hunt.",
     stats=[stat("RP",200,2600000,200000), stat("RP",220,3900000,400000), stat("MS",220,3200000,600000)],
     quests=["The Secret Library Quest (dostęp do rozdziałów)"],
     difficulty=5, risk=5, damageTypes=["fire","death","earth"],
     monsters=[{"name":"Book creatures","slug":"cult-scholar"},{"name":"Mean Lost Soul","slug":"mean-lost-soul"}],
     pulling="Każdy rozdział ma inny element — dobierz resisty.",
     rotation="Ch. II dla 200–300, III/IV od 275+.",
     hero="bookworld3.jpg", video={"title":"Book World Chapter III (TibiaPal)","url":"https://youtu.be/B41VVx0m2mo"},
     sources=[TP,TM], alternatives=["yalahar-grim-reapers","asura-mirror"])

spot(id="iksupan-last-stand", name="Iksupan Last Stand / Occupied Sanctuary", region="Kraina Iks", continent="Kilmaresh",
     city="Kilmaresh", coords={"x":33810,"y":31490,"z":10,"approx":True},
     levelMin=275, levelMax=500, recLevel="300–450",
     vocations=["MS","RP","EK"],
     description="Głębsze partie Iksupan: sanktuarium i ostatnia obrona. MS: 4.4–5.6kk/h dla 275–450.",
     stats=[stat("MS",275,4500000,1000000), stat("RP",300,4700000,300000)],
     quests=["Dostęp do Iksupan"],
     difficulty=5, risk=5, damageTypes=["physical","earth","energy"],
     monsters=[{"name":"Iks elites","slug":"lizard-magistratus"},{"name":"Iks zealots","slug":"lizard-zaogun"}],
     pulling="Elity Iks mają mocne beamy — nie stój w liniach.",
     rotation="Last Stand od wejścia, Sanctuary od 350+.",
     hero="iksupan-last.jpg", video={"title":"Iksupan Last Stand (TibiaPal)","url":"https://youtu.be/0Y7APDNlL70"},
     sources=[TP], alternatives=["iksupan","issavi-crypts"])

spot(id="weretigers", name="Weretigers –1/–2 (Oskayaat)", region="Oskayaat", continent="Kilmaresh",
     city="Issavi", coords={"x":33850,"y":31450,"z":9,"approx":True},
     levelMin=300, levelMax=550, recLevel="300–500",
     vocations=["RP","MS","EK"],
     description="Were-tygrysy w Oskayaat. RP: 4.3–4.4kk/h dla 300+. Earth/ice resisty zalecane.",
     stats=[stat("RP",300,4300000,800000), stat("MS",300,4000000,700000,"estimate")],
     difficulty=5, risk=5, damageTypes=["earth","physical"],
     monsters=[{"name":"Weretiger","slug":"weretiger"}],
     resistances=["earth"],
     pulling="Tygrysy skaczą — trzymaj dystans RP/MS.",
     rotation="–1 dla 300–400, –2 od 400+.",
     hero="weretigers2.jpg", video={"title":"Weretigers -2 (TibiaPal)","url":"https://youtu.be/DzKFptE03_U"},
     sources=[TP], alternatives=["werehyaenas","werecrocodiles"])

spot(id="werecrocodiles", name="Werecrocodiles –1 (Oskayaat)", region="Oskayaat", continent="Kilmaresh",
     city="Issavi", coords={"x":33860,"y":31430,"z":9,"approx":True},
     levelMin=300, levelMax=550, recLevel="300–500",
     vocations=["MS","RP","EK"],
     description="Were-krokodyle Oskayaat: MS 3.9kk/h, dobry profit. Ice resist bardzo pomaga.",
     stats=[stat("MS",300,3900000,600000), stat("RP",300,3800000,600000,"estimate")],
     difficulty=5, risk=5, damageTypes=["ice","physical"],
     monsters=[{"name":"Werecrocodile","slug":"werecrocodile"}],
     resistances=["ice"],
     pulling="Krokodyle mają mocny swipe — blokuj EK w przejściach.",
     rotation="Jedna pętla po kanałach –1.",
     hero="werecrocs.jpg", video={"title":"Werecrocodiles -1 (TibiaPal)","url":"https://youtu.be/GPc65sHAzY0"},
     sources=[TP], alternatives=["weretigers","werehyaenas"])

spot(id="netherworld", name="Netherworld (Lost Souls)", region="Wymiar dusz", continent="Zao",
     city="—", coords={"x":33400,"y":32100,"z":10,"approx":True},
     levelMin=400, levelMax=600, recLevel="400–550",
     vocations=["MS","RP"],
     description="Netherworld z lost souls (Intibia MS 400+: 2.4–4kk/h, profit -100k do +300k). Wysoki exp o dużym rozrzucie.",
     stats=[stat("MS",400,3200000,100000)],
     difficulty=5, risk=5, damageTypes=["death","earth"],
     monsters=[{"name":"Mean Lost Soul","slug":"mean-lost-soul"},{"name":"Freakish Lost Soul","slug":"freakish-lost-soul"},{"name":"Flimsy Lost Soul","slug":"flimsy-lost-soul"}],
     resistances=["death"],
     pulling="Dusze nakładają dużo debuffów — graj defensywnie.",
     rotation="Pętla po krawędziach wymiaru.",
     hero=None, sources=[IN], alternatives=["flimsy-lost-souls","yalahar-grim-reapers"])

spot(id="gazer-spectres", name="Gazer Spectres", region="Netherlands? / okolice Liberty Bay", continent="Tiquanda",
     city="Liberty Bay", coords={"x":32670,"y":32652,"z":7,"approx":False},
     levelMin=250, levelMax=450, recLevel="300–420",
     vocations=["RP","EK","MS"],
     description="Upiorne gaze (Haunted Temple, marker tibiamaps). RP: 3.0kk/h dla 250+. Ice resist + holy bronie.",
     stats=[stat("RP",250,3000000,300000)],
     difficulty=5, risk=4, damageTypes=["energy","death"],
     monsters=[{"name":"Gazer Spectre","slug":"gazer-spectre"}],
     resistances=["energy","death"],
     pulling="Gazery odbijają ataki fizyczne — magią/dystansem.",
     rotation="Świątynia główna bez krypty.",
     hero="gazer.jpg", video={"title":"Gazer Spectres (TibiaPal)","url":"https://youtu.be/CMXG-cVY6BY"},
     sources=[TP,TM], alternatives=["netherworld","asura-mirror"])

spot(id="burster-spectres", name="Burster Spectres", region="Okolice Yalahar", continent="Zao",
     city="Yalahar", coords={"x":32720,"y":31320,"z":8,"approx":True},
     levelMin=300, levelMax=550, recLevel="350–500",
     vocations=["MS","RP","EK"],
     description="Wybuchowe upiory: MS 4.0kk/h dla 275+. Pilnuj HP — burstery eksplodują przy śmierci.",
     stats=[stat("MS",275,4000000,300000), stat("RP",300,3300000,100000)],
     difficulty=5, risk=5, damageTypes=["energy"],
     monsters=[{"name":"Burster Spectre","slug":"burster-spectre"}],
     resistances=["energy"],
     pulling="Nie dobijaj kilku naraz — eksplozje się sumują.",
     rotation="Pętla po sali głównej.",
     hero="burster.jpg", video={"title":"Burster Spectres (TibiaPal)","url":"https://youtu.be/0YgIVSurv_w"},
     sources=[TP], alternatives=["gazer-spectres","ripper-spectres"])

spot(id="ripper-spectres", name="Ripper Spectres", region="Nawiedzony dom", continent="Zao",
     city="Yalahar", coords={"x":32730,"y":31310,"z":8,"approx":True},
     levelMin=350, levelMax=600, recLevel="400–550",
     vocations=["RP","EK","MS"],
     description="Ripper spectres w haunted house: RP 4.1kk/h dla 300+. Mocny fizyczny dmg — mitigation ważny.",
     stats=[stat("RP",300,4100000,500000), stat("EK",400,4000000,500000,"estimate")],
     difficulty=5, risk=5, damageTypes=["physical","energy"],
     monsters=[{"name":"Ripper Spectre","slug":"ripper-spectre"}],
     resistances=["physical"],
     pulling="Ripperzy szybko doskakują — trzymaj wąskie wejścia.",
     rotation="Pokoje domu po kolei.",
     hero="ripper.jpg", video={"title":"Ripper Spectres (TibiaPal)","url":"https://youtu.be/0InUirPg2To"},
     sources=[TP], alternatives=["burster-spectres","gazer-spectres"])

spot(id="true-asuras", name="True Asuras / Asura Citadel", region="Cytadela Asur", continent="Kilmaresh",
     city="—", coords={"x":33894,"y":32713,"z":7,"approx":False},
     levelMin=800, levelMax=1400, recLevel="1000+",
     vocations=["RP","EK","MS"],
     description="Cytadela true asur (realny marker tibiamaps) — endgame 800–1000+. Najwyższe surowe wartości expu w bazie.",
     stats=[stat("RP",1000,9000000,1500000,"estimate"), stat("EK",1000,8500000,1200000,"estimate")],
     dataQuality="estimate",
     difficulty=5, risk=5, damageTypes=["energy","fire","earth"],
     monsters=[{"name":"True Midnight Asura","slug":"true-midnight-asura"},{"name":"True Dawnfire Asura","slug":"true-dawnfire-asura"}],
     resistances=["energy"],
     pulling="True asury mają największe beamy w grze — full respect.",
     rotation="Cytadela od bramy głównej.",
     hero=None, sources=[TP,TM], alternatives=["asura-mirror","cobra-bastion"])

spot(id="ferumbras-seals", name="Ferumbras Ascension — Seals", region="Cytadela Ferumbrasa", continent="Kilmaresh",
     city="—", coords={"x":33330,"y":31400,"z":12,"approx":True},
     levelMin=500, levelMax=1100, recLevel="600–1000",
     vocations=["EK","RP","MS"],
     description="Pieczenie (seals) z questa Ferumbras Ascension: Infernatil, DT, Verminor, Pumin. Endgame'owe hunty o ogromnym expie.",
     stats=[stat("EK",600,6000000,800000,"estimate"), stat("RP",500,5500000,700000,"estimate")],
     dataQuality="estimate",
     quests=["Ferumbras Ascension Quest (aktywne seals)"],
     difficulty=5, risk=5, damageTypes=["fire","physical","earth","energy"],
     monsters=[{"name":"Seal creatures","slug":"demon"},{"name":"Juggernaut","slug":"juggernaut"}],
     modes=["solo","duo","party"], partyRec="Party 4–5 osób: EK + ED + DPS",
     pulling="Każdy seal ma inną taktykę — check guide przed wejściem.",
     rotation="Seals rotacyjnie zależnie od cooldownów.",
     hero=None, sources=[TP], alternatives=["roshamuul-prison","true-asuras"])

# ------------------------------------------------------------ derived values
VOCNAMES = {"EK":"Elite Knight","RP":"Royal Paladin","MS":"Master Sorcerer","ED":"Elder Druid","MNK":"Monk"}

def derive(s):
    xs = [st["xph"] for st in s["stats"] if st.get("xph")]
    ps = [st["profit"] for st in s["stats"] if st.get("profit") is not None]
    s["expPerHour"] = {"min": min(xs), "max": max(xs), "avg": round(sum(xs)/len(xs))} if xs else None
    if ps:
        s["profitPerHour"] = {"min": min(ps), "max": max(ps), "avg": round(sum(ps)/len(ps))}
    else:
        s["profitPerHour"] = None
    waste = max(0, -(min(ps) if ps else 0))
    s["wastePerHour"] = {"max": waste} if waste else {"max": 0}
    s["expByLevel"] = [
        {"range": f"{st['minLevel']}+", "vocation": st["vocation"], "xph": st["xph"], "profit": st.get("profit")}
        for st in sorted(s["stats"], key=lambda x: x["minLevel"]) if st.get("xph")
    ]
    s["slug"] = s["id"]
    if "sources" not in s:
        s["sources"] = [TP]
    s["sources"] = (s.get("sources") or []) + s.get("extra_sources", [])
    for m in s["monsters"]:
        path = f"public/images/monsters/{m['slug']}.png"
        m["img"] = f"/images/monsters/{m['slug']}.png" if os.path.exists(path) else None
    if s.get("hero") and not os.path.exists(f"public/images/screens/{s['hero']}"):
        s["hero"] = None
    return s

SPOTS = [derive(s) for s in SPOTS]
os.makedirs("data", exist_ok=True)
with open("data/spots.json", "w", encoding="utf-8") as f:
    json.dump(SPOTS, f, ensure_ascii=False, indent=1)
print(f"Wrote {len(SPOTS)} spots -> data/spots.json")
